ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name="cart"
urlpatterns = [
    path('addtocart/<n>',views.addtocart,name="addtocart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('full_remove/<n>',views.full_remove,name="full_remove"),
    path('oderform',views.oderform,name="oderform"),
    path('orderview',views.orderview,name="orderview"),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
   urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name="search"
urlpatterns = [
    path('',views.search,name="search"),


]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [

    path('',views.allcategories,name="allcat"),
    path('allprod/<p>',views.allproducts,name="allprod"),
    path('detail/<p>',views.detail,name="detail"),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price

class Order(models.Model):
    product=models.ForeignKey(product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    ordered_date=models.DateTimeField(auto_now_add=True)
    address=models.TextField()
    phone=models.IntegerField()
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    def __str__(self):
        return self.product.name

class Account(models.Model):
     acctnum=models.IntegerField()
     accttype=models.CharField(max_length=20)
     amount=models.IntegerField()
     def __str__(self):
         return str(self.acctnum)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField()
    image=models.ImageField(upload_to="images/category",null=True,blank=True)
    def __str__(self):
        return self.name

class product(models.Model):
    name=models.CharField(max_length=20)
    desc = models.TextField()
    image = models.ImageField(upload_to="images/product", null=True, blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now=True)
    updated=models.DateTimeField(auto_now=True)
    def str(self):
        return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from shop.models import product
from cart.models import Cart,Order,Account
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
@login_required
# Create your views here.
def cartview(request):
    u=request.user
    cart=Cart.objects.filter(user=u)
    total = 0
    for i in cart:
        total += i.quantity * i.product.price
    return render(request,'cartview.html',{'c':cart,'total':total})

@login_required
def addtocart(request,n):
    p=product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(p.stock > 0):
            cart.quantity+=1
            cart.save()
            p.stock-=1
            p.save()
    except:
        if(p.stock > 0):
           cart=Cart.objects.create(product=p,user=u,quantity=1)
           cart.save()
           p.stock-=1
           p.save()
    return cartview(request)
@login_required
def  cart_remove(request,n):
     p=product.objects.get(name=n)
     u=request.user
     try:
         cart=Cart.objects.get(user=u,product=p)
         if(cart.quantity>1):
             cart.quantity -= 1
             cart.save()
             p.stock += 1
             p.save()
         else:
             cart.delete()
             p.stock += 1
             p.save()
     except:
         pass

     return cartview(request)

@login_required
def full_remove(request,n):
    p = product.objects.get(name=n)
    u = request.user
    try:
        cart=Cart.objects.get(user=u, product=p)

        cart.delete()
        p.stock +=cart.quantity
        p.save()
    except:
        pass

    return cartview(request)
@login_required
def oderform(request):
    if(request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)
        total = 0
        for i in cart:
            total += i.quantity * i.product.price

        try:
            num=int(n)
            ac=Account.objects.get(acctnum=num)
            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="Your Order Placed Successfully"
                return render(request,'orderdetail.html',{'msg':msg})
            else:
                msg="Insufficient Amount.You can't place Order"
                return render(request, 'orderdetail.html', {'msg': msg})
        except:
            pass


    return render(request,'oderform.html')

@login_required
def orderview(request):
    u=request.user
    o=Order.objects.filter(user=u)

    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import product
from django.db.models import  Q

# Create your views here.
def search(request):
    query=""
    products=None
    if(request.method=="POST"):
        query=request.POST['q']
        if(query):
            products=product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))

    return render(request,'search.html',{'query':query,'p':products})

ecommerce/shop/views.py
from django.shortcuts import render,redirect
from shop.models import Category,product
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from  django.contrib.auth import login,logout,authenticate
from django.contrib.auth.models import User
def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})
def allproducts(request,p):
    c=Category.objects.get(name=p)
    p=product.objects.filter(category=c)
    return render(request,'product.html',{'c':c,'p':p})
def detail(request,p):
    p=product.objects.get(name=p)
    return render (request,'detail.html',{'p':p})
def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        cp=request.POST['cp']
        fname=request.POST['f']
        lname=request.POST['l']
        e=request.POST['e']


        if(p==cp):
            user=User.objects.create_user(username=u,password=p,first_name=fname,last_name=lname,email=e)
            user.save()
            return redirect('shop:allcat')
        else:
            return HttpResponse("passwords are not match")
    return render(request,'register.html')


def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p= request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            return HttpResponse("Invalid Credentials")
    return render(request,'login.html')
@login_required
def user_logout(request):
    logout(request)
    return redirect('shop:login')

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,100&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>

<header>
    <div class="container-fluid mb-2">
        <center><img src="{% static 'images/img_1.png' %}" height="200px" width="200px"></center>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">MY SHOP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link"  href="{% url 'shop:allcat' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allprod' i.name %}">{{i.name}}</a></li>
              {% endfor %}</ul>
        </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}" >Logout</a>
          </li>
           {% if user.is_superuser == False %}
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping me-5"><sub class="ms-1">{{count}}</sub></i></a>
        </li>
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'cart:orderview' %}">Your Orders</a>
        </li>
          {% endif %}
          {% else %}
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
            <a class="nav-link"  href="{% url 'shop:login' %}">login</a>
        </li>

          {% endif %}


      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
          {% csrf_token %}
        <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
</header>
{% block content %}

{% endblock %}
<footer>
    <div class="footer">

        <p><i class="fa-solid fa-copyright">Myshop pvt ltd.all rights Reserved</i></p>
    </div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
 {% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container"  style="margin-bottom:100px;">
<div class="row">
    <h4 class="text-center fs-4">Shopping Cart</h4>
    <div class="col-7">
        <table class="table table-bordered text-center fs-5">
        <tr>
            <th colspan="5">Cart Items</th>
        </tr>
        {% for i in c %}
        <tr>
            <td><img src="{{i.product.image.url}}" height="150px"  width="100px"></td>
            <td><b>{{i.product.name}}</b></td>
            <td><b>ProductID:{{i.product.id}}</b><br>
                <b>Unit Price:{{i.product.price}}</b><br>
                <b>Quantity:{{i.quantity}}*{{i.product.price}}</b><br>
            </td>
            <td><b>subtotal:{{i.subtotal}}</b></td>
            <td>
                {% if i.product.stock > 0 %}
        <td>
                <a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-danger fs-6"></i></a>
            <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-6"></i></a>
            <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-6"></i></a>
                {% else %}
        <td>

     <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-danger fs-6"></i></a>
     <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-danger fs-6"></i></a></td>
{% endif %}


        {% endfor %}
    </table></div>
<div class="col-4 ms-3 fs-5" style="position:relative;">
    <table class="table table-bordered">
    <tr>
    <th colspan="5">Check Out</th>
</tr>
        <tr><th>Total Amount:<span style="position:absolute;right:20px;">{{total}}</span></th></tr>
</table>
    <a href="{% url 'cart:oderform' %}" class="btn btn-danger">Place order</a>
    <a href="{% url 'shop:allcat' %}" class="btn btn-danger" style="position:absolute;right:20px;">Continue Shopping</a>

</div>

</div>
</div>

{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <img src="{% static 'images/img_8.png' %}" height="400px" width="100%">
</div>

<div class="container-fluid mt-4" style="margin-bottom:100px;">
   <center><h3 class="text-align:center">Our Collections</h3></center>
    <p style="text-align:justify;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<div class="container-fluid mt-4" style="margin-bottom:100px;">
<div class="row">
    {% for i in c %}
    <div class="col-sm-4">
<div class="card" style="width: 30rem;">
  <img src="{{i.image.url}}"height="200px" width="100%" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card title">{{i.name}}</h5>

    <a href="{% url 'shop:allprod' i.name %}" style="position:relative,left:44%;" class="btn btn-primary">products</a>
  </div>
</div>
    </div>{% endfor %}
</div>
</div>
{% endblock %}

ecommerce/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4">
           <img  src="{{p.image.url}}" height="400px" width="400px">
        </div>
        <div class="col-sm-6">
            <h2>{{p.name}}</h2>
            <p class="h4 mt-5 lh-base" style="text-align:justify;">{{p.desc}}</p>
            <h2 class="mt-4">{{p.price}}</h2>
            {{p.stock}}
            {% if user.is_superuser == True %}
            {% if p.stock == 0 %}

            <h2>Out of stock</h2>
            <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
            {% else %}
            <h2>Product in stock</h2>
            <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
            {% endif %}

            {% else %}

            {% if p.stock == 0 %}
            <h2>Out of stock</h2>
            {% else %}
            <a href="{% url 'cart:addtocart' p.name  %}" class="btn btn-danger mt-5">ADD TO CART</a>
            {% endif %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container"  style="margin-bottom:100px;">
<center>
<h3 class="mt-4">login</h3>
    <form method="POST">
    {% csrf_token %}
<div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter the username">
  </div>
<div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter the password">
  </div>

<div class="mb-3">

    <input type="submit" class="form-control">
  </div>
    </form>
</center>
    </div>
{% endblock %}

ecommerce/templates/oderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="">
    <center>
        <h3 class="text-center">Order Form</h3>
        <form method="POST">
    {% csrf_token %}
<div class="mb-3">
    <label class="form-label">Address</label>
    <input type="text" class="form-control" name="a" placeholder="Enter the Address">
  </div>
<div class="mb-3">
    <label class="form-label">Phone</label>
    <input type="number" class="form-control" name="p" placeholder="Enter the phone number">
  </div>
<div class="mb-3">
    <label class="form-label">Account Number</label>
    <input type="Number" class="form-control" name="n" placeholder="Enter the account number">
  </div>


<div class="mb-3">

    <input type="submit" class="form-control">
  </div>
    </form>


</div>
{% endblock %}

ecommerce/templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <center>
        <h4 class="text-center text-success">{{msg}}</h4>
        <h4 class="text-center text-danger">Thank you...</h4>
        <h4 class="text-center"><a href="{% url 'shop:allcat' %}">Continue shopping</a></h4>
    </center>
</div>
{% endblock %}

ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="row mt-5">
        <h4  class="text-danger">Name Of The Customer:{{u}}</h4>
        {% for i in o %}
        <div class="col-sm-4 mt-3" style="margin-left:100px;">

           <img src="{{i.product.image.url}}" height="200px" width="200px">
        </div>
        <div class="col-sm-6  text-center mt-3">
            <b>Product Name:{{i.product.name}}</b><br>
            <b>Product Price:{{i.product.price}}</b><br>
            <b>Delivery Address:{{i.address}}</b><br>
            <b>Customer Phone:{{i.phone}}</b><br>
            <b>Ordered on:{{i.ordered_date}}</b><br>
            <b class="text-success">Delivery_status:{{i.delivery_status}}</b><br>

        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

ecommerce/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
      <img src="{{c.image.url}}" height="450px" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">{{c.name}}</h3>
    <p style="...">{{c.desc}}</p>
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
      <div class="row">
            {% for i in p %}
            <div class="col-sm-4">
                  <div class="card" style="...">
                        <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                              <h5 class="card-title text-center">{{i.name}}</h5>
                                <h6 class="card-title text-center">{{i.price}}</h6>
                              <a href="{% url 'shop:detail' i.name %}" style="position:relative;left:42%;" class="btn btn-primary">details</a>
                        </div>
                  </div>
            </div>{% endfor %}
      </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
 {% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container"  style="margin-bottom:100px;">
<center><h3 class="mt-4">register here</h3>
<form method="POST">
    {% csrf_token %}
<div class="mb-3">
    <label class="form-label">Username</label>
    <input type="text" class="form-control" name="u" placeholder="Enter the username">
  </div>
<div class="mb-3">
    <label class="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="Enter the password">
  </div>
<div class="mb-3">
    <label class="form-label">Confirm password</label>
    <input type="password" class="form-control" name="cp" placeholder="Enter the confirm password">
  </div>
    <div class="mb-3">
    <label class="form-label">first name</label>
    <input type="text" class="form-control" name="f" placeholder="Enter the first name">
  </div>
    <div class="mb-3">
    <label class="form-label">last name</label>
    <input type="text" class="form-control" name="l" placeholder="Enter the last name">
  </div>
    <div class="mb-3">
    <label class="form-label">email</label>
    <input type="text" class="form-control" name="e" placeholder="Enter the email">
  </div>

<div class="mb-3">

    <input type="submit" class="form-control">
  </div>
    </form></center>
</div>

{% endblock %}

ecommerce/templates/search.html
<!DOCTYPE html>
 {% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container"  style="margin-bottom:100px;">
<center>
    <h5> You Have Searched For{{query}}</h5>
    {% if p %}

      <div class="row">
            {% for i in p %}
            <div class="col-sm-3" style="margin-right:10px;margin-bottom:10px;">
                  <div class="card" style="width:18rem">
                        <img src="{{i.image.url}}" height="200px" width="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                              <h5 class="card-title text-center">{{i.name}}</h5>
                                <h6 class="card-title text-center">{{i.price}}</h6>
                              <a href="{% url 'shop:detail' i.name %}" style="position:relative;left:42%;" class="btn btn-primary">details</a>
                        </div>
                  </div>
            </div>{% endfor %}
            </div>



    {% else %}
    <h6 class="text-center">no results found</h6>
    {% endif %}
</center>
</div>
{% endblock %}